import nodemailer from 'nodemailer';
import { config } from '../config/index.js';
import fs from 'fs';
import path from 'path';

/**
 * Sends a job alert email containing matched jobs.
 * @param {string} userEmail - User's email
 * @param {object} profile - Parsed resume profile
 * @param {Array} matches - Ranked job matches
 */
export async function sendJobMatchesEmail(userEmail, profile, matches) {
  const recipients = userEmail ? [userEmail] : [];

  console.log(`[Email Service] Preparing job match alert for: ${recipients.join(', ')}`);

  if (!matches || matches.length === 0) {
    console.warn('[Email Service] No job matches to email.');
    return;
  }

  // Build the email HTML body
  const skillsList = (profile?.skills || []).slice(0, 5).join(', ');
  
  let jobItemsHtml = '';
  for (const match of matches) {
    const applyLink = match.jobUrl || '#';
    const reasonsHtml = (match.reasons || []).map(r => `<li>${r}</li>`).join('');
    
    jobItemsHtml += `
      <div style="border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-bottom: 16px; background-color: #ffffff; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
        <h3 style="margin: 0 0 8px 0; color: #1e293b; font-size: 18px;">${match.title}</h3>
        <p style="margin: 0 0 8px 0; color: #64748b; font-size: 14px; font-weight: 500;">
          <strong>Company:</strong> ${match.company} | <strong>Location:</strong> ${match.location || 'Remote'} | <strong>Match Score:</strong> <span style="color: #10b981; font-weight: bold;">${match.matchScore}%</span>
        </p>
        <ul style="margin: 0 0 12px 0; padding-left: 20px; color: #475569; font-size: 13px;">
          ${reasonsHtml}
        </ul>
        ${applyLink !== '#' ? `<a href="${applyLink}" target="_blank" style="display: inline-block; background-color: #2563eb; color: #ffffff; padding: 8px 16px; border-radius: 6px; text-decoration: none; font-size: 13px; font-weight: 600;">Apply on LinkedIn</a>` : '<span style="color: #94a3b8; font-size: 12px; font-style: italic;">No direct link available</span>'}
      </div>
    `;
  }

  const emailHtml = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>Your AI Job Recommendations</title>
      </head>
      <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f8fafc; padding: 24px; margin: 0; color: #334155;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; border: 1px solid #e2e8f0; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">
          <!-- Header -->
          <div style="background: linear-gradient(135deg, #1e3a8a 0%, #2563eb 100%); padding: 32px 24px; text-align: center; color: #ffffff;">
            <h1 style="margin: 0 0 8px 0; font-size: 24px; font-weight: 700; letter-spacing: -0.025em;">Career Copilot</h1>
            <p style="margin: 0; font-size: 15px; opacity: 0.9;">Real-Time LinkedIn Job Matches & Recommendations</p>
          </div>
          
          <!-- Body -->
          <div style="padding: 32px 24px;">
            <p style="margin-top: 0; font-size: 16px; line-height: 1.6; color: #334155;">
              Hi there,
            </p>
            <p style="font-size: 15px; line-height: 1.6; color: #475569;">
              We parsed your resume and ran a real-time LinkedIn job search for your target role and skills (<span style="background-color: #e2e8f0; padding: 2px 6px; border-radius: 4px; font-size: 13px; font-family: monospace;">${skillsList}</span>).
            </p>
            
            <h2 style="font-size: 18px; color: #1e3a8a; border-bottom: 2px solid #f1f5f9; padding-bottom: 8px; margin-top: 24px; margin-bottom: 16px;">
              Top Job Matches For Your Profile
            </h2>
            
            ${jobItemsHtml}
            
            <p style="font-size: 14px; color: #64748b; line-height: 1.6; margin-top: 24px;">
              Apply to these positions on LinkedIn directly or update your resume using our optimizer to increase your ATS score.
            </p>
          </div>
          
          <!-- Footer -->
          <div style="background-color: #f8fafc; padding: 20px 24px; text-align: center; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8;">
            <p style="margin: 0 0 4px 0;">Generated by AI Career Copilot</p>
            <p style="margin: 0;">This email is related to your uploaded profile matching your skills.</p>
          </div>
        </div>
      </body>
    </html>
  `;

  // Check if SMTP is configured
  if (config.smtpUser && config.smtpPass) {
    try {
      const transporter = nodemailer.createTransport({
        host: config.smtpHost,
        port: config.smtpPort,
        secure: config.smtpPort === 465, // True for 465, false for 587
        auth: {
          user: config.smtpUser,
          pass: config.smtpPass,
        },
      });

      const info = await transporter.sendMail({
        from: config.smtpFrom,
        to: recipients.join(', '),
        subject: 'Career Copilot: Your Real-Time Job Recommendations',
        html: emailHtml,
      });

      console.log(`[Email Service] Email successfully sent: ${info.messageId}`);
      return true;
    } catch (err) {
      console.error(`[Email Service] Failed to send email via SMTP: ${err.message}`);
    }
  }

  // Fallback: Write to console and local file for debugging
  console.log('[Email Service] SMTP Credentials missing or invalid. Writing email content to local debug files...');
  try {
    const dir = path.join(process.cwd(), 'logs');
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    const filePath = path.join(dir, `job-email-${Date.now()}.html`);
    fs.writeFileSync(filePath, emailHtml, 'utf8');
    console.log(`[Email Service] Debug email HTML saved to: ${filePath}`);
  } catch (err) {
    console.error(`[Email Service] Failed to write debug email file: ${err.message}`);
  }
}
